name: RankUp
version: 1.0
main: com.yourname.rankup.RankUp
api-version: 1.20
description: A rank-up plugin for Spigot
author: YourName
commands:
  rankup:
    description: Rank up to the next level
    usage: /rankup
